//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergySolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgileTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgileTeam()
        {
            this.AgileTeamMemberDetails = new HashSet<AgileTeamMemberDetail>();
        }
    
        public int teamId { get; set; }
        public string teamName { get; set; }
        public string teamDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgileTeamMemberDetail> AgileTeamMemberDetails { get; set; }
    }
}
