//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergySolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgileTeamMemberDetail
    {
        public int id { get; set; }
        public int teamId { get; set; }
        public int employId { get; set; }
    
        public virtual AgileTeam AgileTeam { get; set; }
        public virtual EmployInfo EmployInfo { get; set; }
    }
}
