//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergySolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDSavagesEntities : DbContext
    {
        public SDSavagesEntities()
            : base("name=SDSavagesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<AgileTeam> AgileTeams { get; set; }
        public virtual DbSet<AgileTeamMemberDetail> AgileTeamMemberDetails { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<EmployInfo> EmployInfoes { get; set; }
        public virtual DbSet<EmployLogin> EmployLogins { get; set; }
        public virtual DbSet<EmplyDesignation> EmplyDesignations { get; set; }
    }
}
